# Idempotent Auth0 configuration managed by auth0-deploy-cli

clients:
  - name: my-web
    app_type: spa
    oidc_conformant: true
    token_endpoint_auth_method: none
    grant_types:
      - authorization_code
      - refresh_token
    jwt_configuration:
      alg: RS256
    callbacks:
      - http://localhost:3000/callback
      - http://localhost:5173/callback
    allowed_logout_urls:
      - http://localhost:3000
      - http://localhost:5173
    web_origins:
      - http://localhost:3000
      - http://localhost:5173
    allowed_origins:
      - http://localhost:3000
      - http://localhost:5173
    refresh_token:
      rotation_type: rotating
      expiration_type: expiring
      token_lifetime: 2592000     # 30 days
      idle_token_lifetime: 1296000 # 15 days

resourceServers:
  - name: my-api
    identifier: https://api.localhost
    signing_alg: RS256
    allow_offline_access: false
    skip_consent_for_verifiable_first_party_clients: true
    token_lifetime: 7200
    scopes:
      - value: read:todos
        description: Read todos
      - value: write:todos
        description: Create/update todos
      - value: delete:todos
        description: Delete todos

connections:
  - name: Username-Password-Authentication
    strategy: auth0
    options: {}
    enabled_clients:
      - my-web
