name: web-ci
on:
  push:
    paths: ["web/**", ".github/workflows/web.yml"]
  pull_request:
    paths: ["web/**"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Install
        working-directory: web
        run: npm ci || npm install
      - name: Build
        working-directory: web
        run: npm run build
